version: '3'

services:
  alice:
    image: nginx
    container_name: 'alice'
    volumes:
      - ./alice/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  
  bob:
    image: nginx
    container_name: 'bob'
    volumes:
      - ./bob:/usr/share/nginx/html
    ports:
      - 8000:80